Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -64,11 +64,18 @@ jobs:
         username: ${{ secrets.EC2_USER }}
         key: ${{ secrets.EC2_KEY }}
         script: |
-           echo "Stopping previous Spring Boot process if running..."
-           pkill -f 'java -jar' || true
+            echo "Stopping previous app if running..."
+            pkill -f 'java -jar' || true
 
-            echo "Starting Spring Boot app..."
-            nohup java -jar ~/app.jar > app.log 2>&1 < /dev/null &
-            sleep 5
-            echo "App started in background."
-          
+            echo "Starting app..."
+            nohup java -jar ~/app.jar \
+              --DB_HOST =${{ secrets.DB_HOST }} \
+              --DB_USER=${{ secrets.DB_USER }} \
+              --DB_PASS=${{ secrets.DB_PASS }} \
+              --JWT_SECRET=${{ secrets.JWT_SECRET }} \
+              > app.log 2>&1 < /dev/null &
+            
+            sleep 3
+            echo "Checking if app started..."
+            pgrep -f 'java -jar' && echo "App is running" || echo " Failed to start"
+            
